### ISSUE TITLE
datatype-expansion and what happens next

### ISSUE THREAD

**Issue by sichvoge** [raml-org/datatype-expansion#57]
Dear community,

As we want to support you as much as possible, we also want to follow the true community nature and being able to accept contributions with you. We found that this is harder with the implementation that we currently have and decided to migrate the datatype-expansion into JavaScript/TypeScript.

We hope you see that as a chance to also contribute to that project. Additionally, we will be able to better support you with fixes as well. 

Hence, in the next few weeks we will start the migration and also rename that repository to "datatype-expansion" which will include only that. 

We will come back with an ETA asap. 

With the migration, we will tackle the different issues that came up as well of course. Please let us know if there are any concerns from your side.

**Comment by ForsakenHarmony** [comment]
https://github.com/mulesoft-labs/datatype-expansion/tree/develop

currently more of a port

**Comment by sichvoge** [comment]
@ForsakenHarmony, what's the progress on it? Are you feeling comfortable to say it's the same quality than this library already?

**Comment by ForsakenHarmony** [comment]
it's pretty much the same, but could still use some more tests

the fixpoints for recursion are not in and the browser build is not really in yet

**Comment by sichvoge** [comment]
ok.

**Comment by jstoiko** [comment]
update: `datatype-expansion@0.2.0` has been released, it's essentially a drop-in replacement written in JavaScript
