### ISSUE TITLE
object and array types not supported in type array form

### ISSUE THREAD

**Issue by trevorr** [raml-org/datatype-expansion#59]
If `object` or `array` appear in an array of types (i.e. multiple inheritance form), `expandedForm` throws `could not resolve: object` or `could not resolve: array`, respectively. Although this form may not be of much practical value, recent versions of the RAML JS parser seem to always provide a type array.

Also, if `array` is used without `items` (which I believe is permissible by the spec), `expandedForm` throws `form can only be a string or an object` (because it is called recursively with `undefined`) and `canonicalForm` throws `Cannot read property 'type' of undefined`.

Example original types:

```
  ObjectInTypeArray: {
    type: ['object']
  },
  ArrayInTypeArray: {
    type: ['array']
  },
```

Expected expanded types:

```
  ObjectInTypeArray: {
    type: [{ type: 'object' }]
  },
  ArrayInTypeArray: {
    type: [{ type: 'array' }]
  },
```

Expected canonical types:

```
  ObjectInTypeArray: {
    properties: {},
    type: 'object'
  },
  ArrayInTypeArray: {
    items: { type: 'any' },
    type: 'array'
  },
```

**Comment by jstoiko** [comment]
thanks for the PR @trevorr! looks good.

@ForsakenHarmony @antoniogarrote do we need to add anything to [algorithms.md](https://github.com/raml-org/datatype-expansion/blob/master/algorithms.md) to clarify this scenario?
