### ISSUE TITLE
Should canonicalization remove single-element type arrays?

### ISSUE THREAD

**Issue by trevorr** [raml-org/datatype-expansion#68]
The RAML parser always seems to return types as an array, even when there is no multiple inheritance. For instance:

```yaml
  Account:
    properties:
      name: string
```

yields:

```js
{ name: 'Account',
  displayName: 'Account',
  typePropertyKind: 'TYPE_EXPRESSION',
  type: [ 'object' ],
  properties:
   { name:
      { name: 'name',
        displayName: 'name',
        typePropertyKind: 'TYPE_EXPRESSION',
        type: [ 'string' ],
        required: true },
```

Type expansion will then expand `type: [ 'string' ]` to `type: [ { type: 'string' } ]`. Canonicalization will remove inheritance, so that `type: [ 'object' ]` just becomes `type: 'object'`, but the property type expansion remains. However, when an inherited property is canonicalized, it is ultimately flatten (via `min-type`) to string form (e.g. `type: 'string'`). This causes property types to have more than one form after canonicalization, which seems to be, well, non-canonical.

Therefore, should a canonicalization rule be added to convert single-element (property) type arrays into the equivalent non-array form? For instance, if property `p` has a `type` of `[t]`, where `t` is a single element, then a) if `t` is a string, then `type` simply becomes `t`, else b) `t` is an object and `p` is replaced with `Object.assign({}, t, p2)`, where `p2` is a clone of `p` that excludes `type`. This ensures that property attributes (such as `example`) take precedence over type attributes. Alternatively, if b) is undesirable because it potentially loses information, a) could still be done because it is the common case.

Presumably, this would be require a semver breaking change and/or a feature flag.

**Comment by antoniogarrote** [comment]
When you say that

> Canonicalization will remove inheritance, so that type: [ 'object' ] just becomes type: 'object', but the property type expansion remains

Do you mean that after computing the canonical shape we end up with something like:

```clojure
{:properties {"name" {:required true
                      :type ["string"]}}
 :additionalProperties true
 :type "object"}
```

or

```clojure
{:properties {"name" {:required true
                      :type [{:type  "string"}]}}
 :additionalProperties true
 :type "object"}
```

In that case, that's a bug we need to fix.

If the problem is different, could you provide example input and outputs showing the problem?

This is the correct expansion we should be doing according to the documentation:

Input:

```clojure
{:properties {"name" {:required true
                      :type ["string"]}}
 :type [ "object" ]}
```

Expanded form:

```clojure
{:properties {"name" {:required true
                      :type [{:type "string"}]}}
 :additionalProperties true
 :type [{:additionalProperties true
         :type "object"}]}
```

Canonical form:

```clojure
{:properties {"name" {:required true
                      :type "string"}}
 :additionalProperties true
 :type "object"}
```

Notice that by doing ```type: [T]``` you are introducing inheritance, vs ```type: T``` that is just a type declaration. They are not equivalent (although they can render same canonical type at the end).
Be careful passing the output of the RAML parser to the library, the parser is not aware of it.


Thanks.

**Comment by trevorr** [comment]
I'm trying to get raml2html/raml2obj to work with the current version of datatype-expansion. It does pass RAML parser output to this library, but at least in the cases I'm looking at, the input seems to be valid types (with some additional pass-through properties). In one of its tests (in inheritance.raml), it has the following RAML:

```raml
types:
  Email:
    type: string
    pattern: ^.+@.+\..+$
  Account:
    description: A basic account in the inheritance test
    properties:
      name: string
      email: Email
      gender:
        type: string
        enum: [ "male", "female" ]
        required: false
  PasswordProtectedAccount:
    description: An account which is password protected.
    type: Account
    properties:
      password: string
```

After expanding and canonicalizing `PasswordProtectedAccount`:

```js
{ name: 'PasswordProtectedAccount',
  displayName: 'PasswordProtectedAccount',
  typePropertyKind: 'TYPE_EXPRESSION',
  type: [ 'Account' ],
  description: 'An account which is password protected.',
  properties:
   { password:
      { name: 'password',
        displayName: 'password',
        typePropertyKind: 'TYPE_EXPRESSION',
        type: [ 'string' ],
        required: true } } }
```

the result is:

```js
{ type: 'object',
  properties:
   { name:
      { type: 'string',
        name: 'name',
        displayName: 'name',
        typePropertyKind: 'TYPE_EXPRESSION',
        required: true },
     email:
      { type: 'string',
        name: 'email',
        displayName: 'email',
        typePropertyKind: 'TYPE_EXPRESSION',
        pattern: '^.+@.+\\..+$',
        required: true },
     gender:
      { type: 'string',
        name: 'gender',
        displayName: 'gender',
        typePropertyKind: 'TYPE_EXPRESSION',
        required: false,
        enum: [ 'male', 'female' ] },
     password:
      { name: 'password',
        displayName: 'password',
        typePropertyKind: 'TYPE_EXPRESSION',
        type: [ { type: 'string' } ],
        required: true } },
  name: 'PasswordProtectedAccount',
  displayName: 'PasswordProtectedAccount',
  typePropertyKind: 'TYPE_EXPRESSION',
  description: 'An account which is password protected.',
  additionalProperties: true }
```

Note that the inherited properties, `name`, `email`, and `gender`, have `type: 'string'`, whereas the declared property, `password`, has `type: [ { type: 'string' } ]`. All of these properties were originally reported as `type: [ 'string' ]` by the RAML parser. However, due to `min-type` rules, the inherited properties have their type flattened, whereas the declared property does not. This does not seem canonical, since these properties are declared the same way, but end up having different representations after canonicalization.

While I can (and might) try to work around this in raml2obj, it seems like this library might be the best place to address the issue.

**Comment by jstoiko** [comment]
Agreed. Do you have a fix to suggest?

**Comment by trevorr** [comment]
I think the problem is that canonicalization 6 (`Seq[RAMLForm]`) never canonicalizes the `properties` (or array `items` or union `anyOf`) of `form`. The implementation of 6.1.4 recursively canonicalizes the super-types (though this is not explicitly pointed out in the algorithm description), but the sub-type is never canonicalized. I believe simply changing 6.3 to (recursively) canonicalize the result of the `min-type` reduction (instead of only applying `consistency-check`) would address the issue. This is actually what the implementation of canonicalization 5 (`Record[String][RAMLForm]`) does, despite not being called for in the algorithm. (The algorithm says that `type` should be recursively canonicalized, but the implementation actually canonicalizes the result of 5.3 instead.) There might be a more efficient solution, but this seems like the simplest, and it makes cases 5 and 6 more consistent.

**Comment by trevorr** [comment]
I think this issue is fixed in the `develop` branch now (by commit `6b3d407`). If I could get a release with that change (and possibly including #74, if it looks ok), I could update the raml2html/raml2obj dependency on this library from version 0.0.15 to the latest. This was the last fix necessary to get its tests passing.
