### ISSUE TITLE
minType union handling does not preserve non-functional facets

### ISSUE THREAD

**Issue by trevorr** [raml-org/datatype-expansion#88]
Consider the following types:

```js
  T1: {
    displayName: 'T1',
    type: 'object'
  },
  T2: {
    displayName: 'T2',
    type: 'T1'
  },
  T5: {
    displayName: 'T5',
    type: ['T1|T2'],
    properties: {
      kind: 'string'
    }
  }
```

Ideally, the canonical form of `T5` would preserve non-functional facets like `displayName`:

```js
  T5: {
    displayName: 'T5',
    type: 'union',
    anyOf: [{
      displayName: 'T1',
      type: 'object',
      properties: {
        kind: {
          type: 'string',
          required: true
        }
      },
      additionalProperties: true
    }, {
      displayName: 'T2',
      type: 'object',
      properties: {
        kind: {
          type: 'string',
          required: true
        }
      },
      additionalProperties: true
    }]
  }
```

However, the current implementation of `minType` simply uses `T5` as a sub-type to recursively apply to the super-type alternatives `T1` and `T2`. This results in the non-functional facets of `T5` overwriting those of the alternatives and not being applied to the top-level type:

```js
  T5: {
    type: 'union',
    anyOf: [{
      displayName: 'T5',
      type: 'object',
      properties: {
        kind: {
          type: 'string',
          required: true
        }
      },
      additionalProperties: true
    }, {
      displayName: 'T5',
      type: 'object',
      properties: {
        kind: {
          type: 'string',
          required: true
        }
      },
      additionalProperties: true
    }]
  }
```

In the `minType` union cases where one of the types is not a union (7.3 and 7.5), I think it would be better to apply the non-functional facets to the computed/top-level type and apply only the functional facets recursively (7.7). Functional vs non-functional facets are loosely defined in the RAML spec.

**Comment by trevorr** [comment]
Note that this issue is important to me for documentation generation. In the example above, the intended documentation would be:

## T5
(Description of T5)
Union of:
- T1
- T2

The current implementation yields:

## T5 (obtained by key, rather than `displayName`)
(Description lost)
Union of:
- T5
- T5

**Comment by jstoiko** [comment]
how about having something along what we added in #85? I.e. if we kept a reference of the original type, wouldn't we be able to track the original `description/displayName` in this case?

**Comment by trevorr** [comment]
With the final commit of #85, the current behavior with tracking enabled is this:

```js
  T5: {
    type: 'union',
    anyOf: [{
      displayName: 'T5',
      type: 'object',
      originalType: 'T1',
      properties: {
        kind: {
          type: 'string',
          required: true
        }
      },
      additionalProperties: true
    }, {
      displayName: 'T5',
      type: 'object',
      originalType: 'T2',
      properties: {
        kind: {
          type: 'string',
          required: true
        }
      },
      additionalProperties: true
    }]
  }
```

This is now somewhat workable for the aspect of knowing where the alternatives came from.

However, I still think it's a problem in the current minType implementation that the `displayName` and any other facets are not included on the resulting union -- they're only on the alternatives. A documentation generator would not be aware of the reason for this, so it could not generate meaningful documentation for the union itself.
